### PR TITLE
Fix/rebook issues

### LINKED ISSUE #460: Fix Rebooking `No Room Selected` rooms
Not selecting a room in the rebook modal and rebooking results in a booking with "No Room Selected"

https://www.awesomescreenshot.com/video/33205968?key=c4e21d3464aac46d4933de123abea4bd

### PR DESCRIPTION
**Pull request by seayaliu**
# Description & Technical Solution
The problem was in the db file where availabilities were found; it didn't consider edge cases where the start or end of the booking was the same as the start or end of another, which affected both rebooking as well as the booking validators.
- Fix "no room selected" issue
- Fix 30 min overlap

# Checklist
- [X] Already rebased against main branch.

# Issue number
Closes #460 #471

### CODE REVIEW

File: src/slices/hatch/booking-page/db/bookingDb.ts [hunk 1]
```diff
@@ -321,7 +321,7 @@ export const getBookingsInDateRangeForOneRoomDb = async (
           $lte: targetStart,
         },
         endTime: {
-          $gt: targetStart,
+          $gte: targetStart,
```
Comment (HagOrMan) [inline src/slices/hatch/booking-page/db/bookingDb.ts:324]: Good catch!

File: src/slices/hatch/booking-page/hooks/bookingHooks.ts [hunk 2]
```diff
@@ -58,6 +58,7 @@ export const useDeleteBookingHook = () => {
     mutationFn: fetchDeleteBooking,
     onSuccess: () => {
       queryClient.invalidateQueries({ queryKey: ['userBookings'] });
+      queryClient.invalidateQueries({ queryKey: ['allBookings'] });
```
Comment (HagOrMan) [inline src/slices/hatch/booking-page/hooks/bookingHooks.ts:61]: Good fix here

File: src/slices/hatch/dashboard/components/modals/TomorrowModal.tsx [hunk 3]
```diff
@@ -94,19 +96,23 @@ const TomorrowModal: React.FC<TomorrowModalProps> = ({
...
-          toast('Room has been successfully booked.');
-        }
-      },
-      onError: () => {
-        toast('Room booking was unsuccessful.');
-      },
-    });
-    onClose();
+    if (roomSelected != true) {
+      toast('No room selected.');
```
Comment (HagOrMan) [inline src/slices/hatch/dashboard/components/modals/TomorrowModal.tsx:100]: nice!

**Review by HagOrMan — APPROVED** [review]
looks great!
